# Generated by Django 5.0.7 on 2024-08-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_user'),
        ('orders', '0002_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
