# Generated by Django 5.0.7 on 2024-08-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_billinginformation_delete_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
