# Generated by Django 5.0.7 on 2024-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_charges_order_discount_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
