# Generated by Django 5.0.7 on 2024-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
