# Generated by Django 5.0.7 on 2024-08-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderditem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderditem',
            name='price',
        ),
    ]
