# Generated by Django 5.0.4 on 2024-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='theme/')),
                ('main_caption', models.CharField(max_length=150)),
                ('sub_caption', models.TextField(max_length=200)),
            ],
        ),
    ]
